export const campaignListData = {
    "message": "Successfully Processed.",
    "statusCode": 200,
    "data": {
        "content": [
            {
                "id": 11,
                "createdAt": "2025-03-18T21:10:30",
                "updatedAt": "2025-03-18T21:11:45",
                "campaignId": "OD3564822442672129",
                "campaignName": "plem_rewards_demo_1",
                "notificationTitle": "you have unused PLEM Points, save now!",
                "notificationDescription": "don’t let your rewards go to waste! \nyou have unused PLEM Points waiting to be redeemed and happiness is just a few taps away. take advantage of these benefits and make the most out of your loyalty today. redeem now and treat yourself to something special—you’ve earned it! \n\nRedeem Your PLEM Points Now!",
                "notificationImageUrl": null,
                "notificationDeeplink": "https://plem.onelink.me/catalogue",
                "articleTitle": "you have unused PLEM Points, save now!",
                "articleDescription": "don’t let your rewards go to waste! \nyou have unused PLEM Points waiting to be redeemed and happiness is just a few taps away. take advantage of these benefits and make the most out of your loyalty today. redeem now and treat yourself to something special—you’ve earned it! \n\nRedeem Your PLEM Points Now!",
                "articleImageUrl": null,
                "articleDeeplink": "https://plem.onelink.me/catalogue",
                "targetAudience": "[\"9876543210\"]",
                "targetAudienceType": "SPECIFIC_USERS",
                "userId": 3,
                "partnerId": 2,
                "status": "SEGMENT_CREATED",
                "segmentResponse": null,
                "segmentName": "plem_rewards_demo_1_OD3564822442672129",
                "segmentRequestId": null,
                "csvUrl": "https://loyalty-images-upload-test.s3.amazonaws.com/rewards_list.csv",
                "segmentCreated": true,
                "notificationMedium": "Push Notification",
                "scheduleTime": null
            },
            {
                "id": 12,
                "createdAt": "2025-03-18T22:05:10",
                "updatedAt": "2025-03-18T22:06:30",
                "campaignId": "OD3564822442672130",
                "campaignName": "plem_bonus_offer",
                "notificationTitle": "special offer for you – get 20% extra PLEM Points on amazon",
                "notificationDescription": "congratulations! you have an exclusive special offer on an amazon gift card waiting to be redeemed. don’t miss this chance to unlock amazing value and shop your favourite items on amazon. whether it’s gadgets, fashion, home essentials, or more, this is your moment to snag a deal and save big. act fast before this offer expires—treat yourself or surprise someone special with the perfect gift! \n\nclaim your offer now!",
                "notificationImageUrl": null,
                "notificationDeeplink": "https://plem.onelink.me/catalogue",
                "articleTitle": "special offer for you – get 20% extra PLEM Points on amazon",
                "articleDescription": "congratulations! you have an exclusive special offer on an amazon gift card waiting to be redeemed. don’t miss this chance to unlock amazing value and shop your favourite items on amazon. whether it’s gadgets, fashion, home essentials, or more, this is your moment to snag a deal and save big. act fast before this offer expires—treat yourself or surprise someone special with the perfect gift! \n\nclaim your offer now!",
                "articleImageUrl": null,
                "articleDeeplink": "https://plem.onelink.me/catalogue",
                "targetAudience": "[\"9988776655\"]",
                "targetAudienceType": "SPECIFIC_USERS",
                "userId": 4,
                "partnerId": 3,
                "status": "SEGMENT_CREATED",
                "segmentResponse": null,
                "segmentName": "plem_bonus_offer_OD3564822442672130",
                "segmentRequestId": null,
                "csvUrl": "https://loyalty-images-upload-test.s3.amazonaws.com/bonus_offer.csv",
                "segmentCreated": true,
                "notificationMedium": "Push Notification",
                "scheduleTime": null
            },
            {
                "id": 13,
                "createdAt": "2025-03-18T23:15:45",
                "updatedAt": "2025-03-18T23:16:50",
                "campaignId": "OD3564822442672131",
                "campaignName": "plem_box_demo_2",
                "notificationTitle": "Congratulations! You’ve Received SOL Cash",
                "notificationDescription": "you’ve just earned SOL Cash through your recent engagement with solfin \ndon’t miss out on making the most of your rewards. treat yourself to something special or grab a deal before it’s gone. every point counts, so start enjoying your rewards today.",
                "notificationImageUrl": null,
                "notificationDeeplink": "https://plem.onelink.me/catalogue",
                "articleTitle": "Congratulations! You’ve Received SOL Cash",
                "articleDescription": "you’ve just earned SOL Cash through your recent engagement with solfin \ndon’t miss out on making the most of your rewards. treat yourself to something special or grab a deal before it’s gone. every point counts, so start enjoying your rewards today.",
                "articleImageUrl": null,
                "articleDeeplink": "https://plem.onelink.me/catalogue",
                "targetAudience": "[\"9123456789\"]",
                "targetAudienceType": "SPECIFIC_USERS",
                "userId": 5,
                "partnerId": 4,
                "status": "SEGMENT_CREATED",
                "segmentResponse": null,
                "segmentName": "plem_box_demo_2_OD3564822442672131",
                "segmentRequestId": null,
                "csvUrl": "https://loyalty-images-upload-test.s3.amazonaws.com/test_prod.csv",
                "segmentCreated": true,
                "notificationMedium": "Push Notification",
                "scheduleTime": null
            },
            {
                "id": 14,
                "createdAt": "2025-03-19T00:20:30",
                "updatedAt": "2025-03-19T00:21:40",
                "campaignId": "OD3564822442672132",
                "campaignName": "plem_box_demo_4",
                "notificationTitle": "New Feature Alert - Track All Your Loyalty Points on PLEM",
                "notificationDescription": "say goodbye to juggling multiple apps and accounts and hello to convenience! now you can track all your loyalty points from various brands in one place - PLEM. \nwhether it's your favourite coffee shop or retail store or airline, managing rewards has never been easier! take control of your points, redeem smarter, and never miss out on any benefits again. It's time to make your loyalty truly rewarding.\n\ntrack your loyalty points now!",
                "notificationImageUrl": null,
                "notificationDeeplink": "https://plem.in/home",
                "articleTitle": "New Feature Alert - Track All Your Loyalty Points on PLEM",
                "articleDescription": "say goodbye to juggling multiple apps and accounts and hello to convenience! now you can track all your loyalty points from various brands in one place - PLEM. \nwhether it's your favourite coffee shop or retail store or airline, managing rewards has never been easier! take control of your points, redeem smarter, and never miss out on any benefits again. It's time to make your loyalty truly rewarding.\n\ntrack your loyalty points now!",
                "articleImageUrl": null,
                "articleDeeplink": "https://plem.in/home",
                "targetAudience": "[\"9654321870\"]",
                "targetAudienceType": "SPECIFIC_USERS",
                "userId": 6,
                "partnerId": 5,
                "status": "SEGMENT_CREATED",
                "segmentResponse": null,
                "segmentName": "plem_box_demo_4_OD3564822442672132",
                "segmentRequestId": null,
                "csvUrl": "https://loyalty-images-upload-test.s3.amazonaws.com/test_prod.csv",
                "segmentCreated": true,
                "notificationMedium": "Push Notification",
                "scheduleTime": null
            }
        ],
        "pageable": {
            "pageNumber": 0,
            "pageSize": 20,
            "sort": {
                "empty": true,
                "sorted": false,
                "unsorted": true
            },
            "offset": 0,
            "paged": true,
            "unpaged": false
        },
        "last": true,
        "totalElements": 10,
        "totalPages": 1,
        "first": true,
        "size": 20,
        "number": 0,
        "sort": {
            "empty": true,
            "sorted": false,
            "unsorted": true
        },
        "numberOfElements": 10,
        "empty": false
    }
}

export const notificationListData = {
    "message": "Successfully Processed.",
    "statusCode": 200,
    "data": {
        "content": [
            {
                "id": 11,
                "createdAt": "2025-03-18T21:10:30",
                "updatedAt": "2025-03-18T21:11:45",
                "notificationId": "OD3564822442672129",
                "campaignName": "plem_rewards_demo_1",
                "notificationTitle": "you have unused PLEM Points, save now!",
                "notificationDescription": "don’t let your rewards go to waste! \nyou have unused PLEM Points waiting to be redeemed and happiness is just a few taps away. take advantage of these benefits and make the most out of your loyalty today. redeem now and treat yourself to something special—you’ve earned it! \n\nRedeem Your PLEM Points Now!",
                "notificationImageUrl": null,
                "notificationDeeplink": "https://plem.onelink.me/catalogue",
                "articleTitle": "you have unused PLEM Points, save now!",
                "articleDescription": "don’t let your rewards go to waste! \nyou have unused PLEM Points waiting to be redeemed and happiness is just a few taps away. take advantage of these benefits and make the most out of your loyalty today. redeem now and treat yourself to something special—you’ve earned it! \n\nRedeem Your PLEM Points Now!",
                "articleImageUrl": null,
                "articleDeeplink": "https://plem.onelink.me/catalogue",
                "targetAudience": "[\"9876543210\"]",
                "targetAudienceType": "SPECIFIC_USERS",
                "userId": 3,
                "partnerId": 2,
                "status": "SEGMENT_CREATED",
                "segmentResponse": null,
                "segmentName": "plem_rewards_demo_1_OD3564822442672129",
                "segmentRequestId": null,
                "csvUrl": "https://loyalty-images-upload-test.s3.amazonaws.com/rewards_list.csv",
                "segmentCreated": true,
                "notificationMedium": "Push Notification",
                "scheduleTime": null,
                "published": false

            },
            {
                "id": 12,
                "createdAt": "2025-03-18T22:05:10",
                "updatedAt": "2025-03-18T22:06:30",
                "notificationId": "OD3564822442672130",
                "campaignName": "plem_bonus_offer",
                "notificationTitle": "special offer for you – get 20% extra PLEM Points on amazon",
                "notificationDescription": "congratulations! you have an exclusive special offer on an amazon gift card waiting to be redeemed. don’t miss this chance to unlock amazing value and shop your favourite items on amazon. whether it’s gadgets, fashion, home essentials, or more, this is your moment to snag a deal and save big. act fast before this offer expires—treat yourself or surprise someone special with the perfect gift! \n\nclaim your offer now!",
                "notificationImageUrl": null,
                "notificationDeeplink": "https://plem.onelink.me/catalogue",
                "articleTitle": "special offer for you – get 20% extra PLEM Points on amazon",
                "articleDescription": "congratulations! you have an exclusive special offer on an amazon gift card waiting to be redeemed. don’t miss this chance to unlock amazing value and shop your favourite items on amazon. whether it’s gadgets, fashion, home essentials, or more, this is your moment to snag a deal and save big. act fast before this offer expires—treat yourself or surprise someone special with the perfect gift! \n\nclaim your offer now!",
                "articleImageUrl": null,
                "articleDeeplink": "https://plem.onelink.me/catalogue",
                "targetAudience": "[\"9988776655\"]",
                "targetAudienceType": "SPECIFIC_USERS",
                "userId": 4,
                "partnerId": 3,
                "status": "SEGMENT_CREATED",
                "segmentResponse": null,
                "segmentName": "plem_bonus_offer_OD3564822442672130",
                "segmentRequestId": null,
                "csvUrl": "https://loyalty-images-upload-test.s3.amazonaws.com/bonus_offer.csv",
                "segmentCreated": true,
                "notificationMedium": "Push Notification",
                "scheduleTime": null,
                "published": true

            },
            {
                "id": 13,
                "createdAt": "2025-03-18T23:15:45",
                "updatedAt": "2025-03-18T23:16:50",
                "notificationId": "OD3564822442672131",
                "campaignName": "plem_box_demo_2",
                "notificationTitle": "Congratulations! You’ve Received SOL Cash",
                "notificationDescription": "you’ve just earned SOL Cash through your recent engagement with solfin \ndon’t miss out on making the most of your rewards. treat yourself to something special or grab a deal before it’s gone. every point counts, so start enjoying your rewards today.",
                "notificationImageUrl": null,
                "notificationDeeplink": "https://plem.onelink.me/catalogue",
                "articleTitle": "Congratulations! You’ve Received SOL Cash",
                "articleDescription": "you’ve just earned SOL Cash through your recent engagement with solfin \ndon’t miss out on making the most of your rewards. treat yourself to something special or grab a deal before it’s gone. every point counts, so start enjoying your rewards today.",
                "articleImageUrl": null,
                "articleDeeplink": "https://plem.onelink.me/catalogue",
                "targetAudience": "[\"9123456789\"]",
                "targetAudienceType": "SPECIFIC_USERS",
                "userId": 5,
                "partnerId": 4,
                "status": "SEGMENT_CREATED",
                "segmentResponse": null,
                "segmentName": "plem_box_demo_2_OD3564822442672131",
                "segmentRequestId": null,
                "csvUrl": "https://loyalty-images-upload-test.s3.amazonaws.com/test_prod.csv",
                "segmentCreated": true,
                "notificationMedium": "Push Notification",
                "scheduleTime": null,
                "published": true

            },
            {
                "id": 14,
                "createdAt": "2025-03-19T00:20:30",
                "updatedAt": "2025-03-19T00:21:40",
                "notificationId": "OD3564822442672132",
                "campaignName": "plem_box_demo_4",
                "notificationTitle": "New Feature Alert - Track All Your Loyalty Points on PLEM",
                "notificationDescription": "say goodbye to juggling multiple apps and accounts and hello to convenience! now you can track all your loyalty points from various brands in one place - PLEM. \nwhether it's your favourite coffee shop or retail store or airline, managing rewards has never been easier! take control of your points, redeem smarter, and never miss out on any benefits again. It's time to make your loyalty truly rewarding.\n\ntrack your loyalty points now!",
                "notificationImageUrl": null,
                "notificationDeeplink": "https://plem.in/home",
                "articleTitle": "New Feature Alert - Track All Your Loyalty Points on PLEM",
                "articleDescription": "say goodbye to juggling multiple apps and accounts and hello to convenience! now you can track all your loyalty points from various brands in one place - PLEM. \nwhether it's your favourite coffee shop or retail store or airline, managing rewards has never been easier! take control of your points, redeem smarter, and never miss out on any benefits again. It's time to make your loyalty truly rewarding.\n\ntrack your loyalty points now!",
                "articleImageUrl": null,
                "articleDeeplink": "https://plem.in/home",
                "targetAudience": "[\"9654321870\"]",
                "targetAudienceType": "SPECIFIC_USERS",
                "userId": 6,
                "partnerId": 5,
                "status": "SEGMENT_CREATED",
                "segmentResponse": null,
                "segmentName": "plem_box_demo_4_OD3564822442672132",
                "segmentRequestId": null,
                "csvUrl": "https://loyalty-images-upload-test.s3.amazonaws.com/test_prod.csv",
                "segmentCreated": true,
                "notificationMedium": "Push Notification",
                "scheduleTime": null,
                "published": true
            }
        ],
        "pageable": {
            "pageNumber": 0,
            "pageSize": 20,
            "sort": {
                "empty": true,
                "sorted": false,
                "unsorted": true
            },
            "offset": 0,
            "paged": true,
            "unpaged": false
        },
        "last": true,
        "totalElements": 10,
        "totalPages": 1,
        "first": true,
        "size": 20,
        "number": 0,
        "sort": {
            "empty": true,
            "sorted": false,
            "unsorted": true
        },
        "numberOfElements": 10,
        "empty": false
    }
}